Repository linera-io/linera-protocol, pull requests merged in 2023-11, with the labels that each got.

#1190 Create trait `LineraNet` so that e2e tests can drive other types of test nets
  Cargo.lock
  examples/crowd-funding/README.md
  examples/crowd-funding/src/lib.rs
  linera-indexer/example/Cargo.toml
  linera-indexer/example/tests/test.rs
  linera-service-graphql-client/Cargo.toml
  linera-service-graphql-client/tests/test.rs
  linera-service/src/cli_wrappers/local_net.rs
  linera-service/src/cli_wrappers/mod.rs
  linera-service/src/cli_wrappers/wallet.rs
  linera-service/src/linera.rs
  linera-service/src/util.rs
  linera-service/tests/end_to_end_tests.rs
  linera-service/tests/wasm_end_to_end_tests.rs
Labels: refactor

#1148 Run Wasm guest code in separate threads
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  linera-execution/Cargo.toml
  linera-execution/src/wasm/async_boundary.rs
  linera-execution/src/wasm/async_determinism.rs
  linera-execution/src/wasm/common.rs
  linera-execution/src/wasm/guest_futures.rs
  linera-execution/src/wasm/mod.rs
  linera-execution/src/wasm/runtime_actor/handlers.rs
  linera-execution/src/wasm/runtime_actor/mod.rs
  linera-execution/src/wasm/runtime_actor/requests.rs
  linera-execution/src/wasm/system_api.rs
  linera-execution/src/wasm/wasmer.rs
  linera-execution/src/wasm/wasmtime.rs
Labels: enhancement

#1208 Dont panic if the `RuntimeActor` stops
  linera-execution/src/wasm/runtime_actor/mod.rs
  linera-execution/src/wasm/runtime_actor/tests.rs
  linera-execution/src/wasm/system_api.rs
  linera-execution/src/wasm/wasmer.rs
  linera-execution/src/wasm/wasmtime.rs
Labels: bug

#1209 Improve clarity of `RuntimeActor` code
  linera-execution/src/wasm/runtime_actor/mod.rs
Labels: refactor

#1225 Make interface between Wasm guests and the host synchronous
  examples/reentrant-counter/src/service.rs
  linera-execution/src/wasm/async_boundary.rs
  linera-execution/src/wasm/async_determinism.rs
  linera-execution/src/wasm/common.rs
  linera-execution/src/wasm/guest_futures.rs
  linera-execution/src/wasm/mod.rs
  linera-execution/src/wasm/system_api.rs
  linera-execution/src/wasm/wasmer.rs
  linera-execution/src/wasm/wasmtime.rs
  linera-execution/tests/fixtures/counter_contract.wasm
  linera-execution/tests/fixtures/counter_service.wasm
  linera-execution/tests/wasm.rs
  linera-sdk/contract.wit
  linera-sdk/contract_system_api.wit
  linera-sdk/service.wit
  linera-sdk/service_system_api.wit
  linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
  linera-sdk/src/contract/conversions_from_wit.rs
  linera-sdk/src/contract/conversions_to_wit.rs
  linera-sdk/src/contract/exported_futures.rs
  linera-sdk/src/contract/mod.rs
  linera-sdk/src/contract/storage.rs
  linera-sdk/src/contract/system_api.rs
  linera-sdk/src/exported_future.rs
  linera-sdk/src/lib.rs
  linera-sdk/src/service/conversions_from_wit.rs
  linera-sdk/src/service/conversions_to_wit.rs
  linera-sdk/src/service/exported_futures.rs
  linera-sdk/src/service/mod.rs
  linera-sdk/src/service/storage.rs
  linera-sdk/src/service/system_api.rs
  linera-sdk/src/util.rs
  linera-sdk/src/views/conversions_from_wit.rs
  linera-sdk/src/views/mod.rs
  linera-sdk/src/views/system_api.rs
  linera-sdk/view_system_api.wit
Labels: enhancement

#1233 Fix Linera SDK Wasm tests
  .github/workflows/rust.yml
  linera-sdk/src/contract/system_api/mod.rs
  linera-sdk/src/contract/system_api/private.rs
  linera-sdk/src/service/system_api/mod.rs
  linera-sdk/src/service/system_api/private.rs
  linera-sdk/wasm-tests/src/lib.rs
Labels: testing

#1234 Remove `async_determinism` module
  linera-execution/src/wasm/async_determinism.rs
  linera-execution/src/wasm/common.rs
  linera-execution/src/wasm/mod.rs
  linera-execution/src/wasm/system_api.rs
  linera-execution/src/wasm/wasmer.rs
  linera-execution/src/wasm/wasmtime.rs
  linera-sdk/contract_system_api.wit
  linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
  linera-sdk/src/contract/storage.rs
  linera-sdk/src/contract/system_api/private.rs
  linera-sdk/wasm-tests/src/lib.rs
Labels: refactor

#1207 Validators use TLS
  .github/workflows/kubernetes.yml
  .gitignore
  Cargo.lock
  Cargo.toml
  configuration/k8s-local/validator_1.toml
  configuration/local/validator_1.toml
  configuration/local/validator_2.toml
  configuration/local/validator_3.toml
  configuration/local/validator_4.toml
  configuration/prod/validator_1.toml
  docker/Dockerfile
  docker/server-entrypoint.sh
  docker/server-init.sh
  kubernetes/linera-validator/README.md
  kubernetes/linera-validator/build_and_redeploy.sh
  kubernetes/linera-validator/templates/config.yaml
  kubernetes/linera-validator/templates/ingress.yaml
  kubernetes/linera-validator/templates/prometheus.yaml
  kubernetes/linera-validator/templates/proxy.yaml
  kubernetes/linera-validator/templates/server.yaml
  kubernetes/linera-validator/values-dev-gcp.yaml
  kubernetes/linera-validator/values-local-with-cloud-build.yaml
  kubernetes/linera-validator/values-local.yaml
  kubernetes/linera-validator/working/.placeholder
  linera-rpc/src/config.rs
  linera-service/Cargo.toml
  linera-service/src/cli_wrappers/mod.rs
  linera-service/src/grpc_proxy.rs
  linera-service/src/linera.rs
  linera-service/src/proxy.rs
  linera-service/src/server.rs
Labels: infra

#1239 Use a `RwLock` over the contract system runtime to prevent data races
  linera-execution/src/wasm/mod.rs
  linera-execution/src/wasm/runtime_actor/handlers.rs
  linera-execution/src/wasm/runtime_actor/mod.rs
  linera-execution/src/wasm/runtime_actor/requests.rs
  linera-execution/src/wasm/runtime_actor/sync_response.rs
  linera-execution/src/wasm/system_api.rs
  linera-execution/src/wasm/wasmer.rs
  linera-execution/src/wasm/wasmtime.rs
  linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
  linera-sdk/src/views/system_api.rs
  linera-sdk/view_system_api.wit
Labels: bug

#1266 Fix deadlock in `ChainListener`
  linera-service/src/chain_listener.rs
Labels: bug
