Repository linera-io/linera-protocol, pull requests merged in 2024-10, with the labels that each got.

#2533 Move long faucet chain test to different CI workflow
  .github/workflows/long_faucet_chain_test.yml
  linera-service/tests/linera_net_tests.rs
Labels: chore

#2564 Use a shorter chain in the long faucet chain test
  linera-service/tests/linera_net_tests.rs
Labels: testing

#2565 Retry all gRPC requests, not just notification streams.
  CLI.md
  linera-client/src/client_context.rs
  linera-client/src/client_options.rs
  linera-rpc/src/grpc/client.rs
  linera-rpc/src/node_provider.rs
  linera-rpc/tests/transport.rs
Labels: bug

#2573 `README.md`: explain `linera-client`
  README.md
Labels: documentation

#2586 Disable `wat` feature from `wasmer` and `wasmtime`
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  linera-execution/Cargo.toml
  linera-execution/src/wasm/sanitizer.rs
  linera-witty/Cargo.toml
Labels: chore

#2591 Update `wasmer` to version `4.4.0-linera.5`
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
Labels: chore

#2602 Disable `ed25519-dalek` default features
  Cargo.toml
  linera-rpc/src/grpc/conversions.rs
Labels: chore

#2621 Fix unordered application registration messages
  linera-execution/src/execution.rs
Labels: bug

#2625 Fix unordered application registration messages (port to testnet)
  linera-execution/src/execution.rs
Labels: bug

#2635 Fix name of "long-faucet-chain-test" job in CI
  .github/workflows/long_faucet_chain_test.yml
Labels: chore

#2636 Fix performance regression caused by disabling `ed25519-dalek`'s `fast` feature
  Cargo.toml
Labels: performance

#2639 Run long faucet chain test in release mode
  .github/workflows/long_faucet_chain_test.yml
Labels: chore

#2640 Retry node service queries if they timeout
  linera-service/src/cli_wrappers/wallet.rs
Labels: enhancement

#2648 Backport long faucet chain test fixes
  .github/workflows/long_faucet_chain_test.yml
  linera-service/tests/linera_net_tests.rs
Labels: chore

#2656 Fix query target in `ContractRuntime::query_service` documentation
  linera-sdk/src/contract/runtime.rs
  linera-sdk/src/contract/test_runtime.rs
Labels: documentation

#2670 Fix query target in `ContractRuntime::query_service` documentation (port to testnet)
  linera-sdk/src/contract/runtime.rs
  linera-sdk/src/contract/test_runtime.rs
Labels: documentation

#2689 Move delivery notifiers to chain worker
  linera-core/src/chain_worker/actor.rs
  linera-core/src/chain_worker/delivery_notifier.rs
  linera-core/src/chain_worker/mod.rs
  linera-core/src/chain_worker/state/attempted_changes.rs
  linera-core/src/chain_worker/state/mod.rs
  linera-core/src/worker.rs
Labels: bug

#2702 Use scylla production mode but disable it in CI
  .github/workflows/docker.yml
  docker/docker-compose.yml
Labels: chore

#2711 Skip reading environment variable and allocating a `String` if possible
  linera-service/src/cli_wrappers/remote_net.rs
Labels: refactor, testing

#2713 Don't fallback to hardcoded devnet Faucet URL
  linera-service/src/cli_wrappers/remote_net.rs
Labels: testing

#2718 Fix insufficient balance error messages in long faucet chain test
  linera-service/tests/linera_net_tests.rs
Labels: testing

#2721 Fix faucet timeout in long faucet chain test
  linera-service/src/cli_wrappers/wallet.rs
  linera-service/tests/linera_net_tests.rs
Labels: testing

#2724 Port long faucet chain test fixes to devnet
  linera-service/src/cli_wrappers/wallet.rs
  linera-service/tests/linera_net_tests.rs
Labels: testing

#2722 Fix conversion of `SystemMessage::OpenChain` message to `async_graphql::Value`
  linera-base/src/identifiers.rs
Labels: bug
