Repository linera-io/linera-protocol, pull requests merged in 2024-01, with the labels that each got.

#1428 Remove actor execution runtime
  linera-execution/src/execution.rs
  linera-execution/src/execution_state_actor.rs
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/runtime_actor/handlers.rs
  linera-execution/src/runtime_actor/requests.rs
  linera-execution/src/runtime_actor/senders.rs
  linera-execution/src/runtime_actor/tests.rs
  linera-execution/src/sync_runtime.rs
  linera-execution/src/util/mod.rs
  linera-execution/src/util/sync_response.rs
  linera-execution/src/wasm/mod.rs
  linera-execution/tests/test_execution.rs
  linera-execution/tests/wasm.rs
Labels: chore

#1431 Make `try-query-application` system API synchronous
  examples/meta-counter/src/service.rs
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/wasm/system_api.rs
  linera-sdk/service_system_api.wit
  linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
  linera-sdk/src/lib.rs
  linera-sdk/src/service/system_api/private.rs
  linera-sdk/wasm-tests/src/lib.rs
Labels: enhancement

#1437 Remove support for reentrant application calls
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  examples/Cargo.toml
  examples/amm/src/contract.rs
  examples/crowd-funding/src/contract.rs
  examples/matching-engine/src/contract.rs
  examples/meta-counter/src/contract.rs
  examples/reentrant-counter/Cargo.toml
  examples/reentrant-counter/src/contract.rs
  examples/reentrant-counter/src/lib.rs
  examples/reentrant-counter/src/service.rs
  examples/reentrant-counter/src/state.rs
  linera-core/Cargo.toml
  linera-core/src/unit_tests/wasm_client_tests.rs
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/tests/test_execution.rs
  linera-execution/tests/utils.rs
  linera-execution/tests/wasm.rs
  linera-sdk/src/contract/storage.rs
  linera-sdk/src/contract/system_api/mod.rs
  linera-sdk/src/contract/system_api/private.rs
  linera-sdk/src/lib.rs
Labels: enhancement

#1441 Remove locking system APIs
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/wasm/system_api.rs
  linera-execution/src/wasm/wasmtime.rs
  linera-execution/tests/fixtures/counter_contract.wasm
  linera-execution/tests/fixtures/counter_service.wasm
  linera-execution/tests/test_execution.rs
  linera-execution/tests/wasm.rs
  linera-sdk/contract_system_api.wit
  linera-sdk/mock_system_api.wit
  linera-sdk/service_system_api.wit
  linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
  linera-sdk/src/contract/storage.rs
  linera-sdk/src/contract/system_api/mod.rs
  linera-sdk/src/contract/system_api/private.rs
  linera-sdk/src/service/storage.rs
  linera-sdk/src/service/system_api/mod.rs
  linera-sdk/src/service/system_api/private.rs
  linera-sdk/src/test/unit/mod.rs
  linera-sdk/wasm-tests/src/lib.rs
Labels: chore

#1455 Remove simple state storage APIs
  linera-execution/src/execution.rs
  linera-execution/src/execution_state_actor.rs
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/wasm/system_api.rs
  linera-execution/src/wasm/wasmtime.rs
  linera-execution/tests/fixtures/counter_contract.wasm
  linera-execution/tests/fixtures/counter_service.wasm
  linera-execution/tests/test_execution.rs
  linera-sdk/contract_system_api.wit
  linera-sdk/service_system_api.wit
Labels: refactor

#1463 Remove `String` error types from APIs to query other application services
  linera-execution/src/wasm/system_api.rs
  linera-sdk/mock_system_api.wit
  linera-sdk/service_system_api.wit
  linera-sdk/src/bin/linera-wasm-test-runner/mock_system_api.rs
  linera-sdk/src/lib.rs
  linera-sdk/src/service/system_api/private.rs
  linera-sdk/src/test/unit/mod.rs
  linera-sdk/wasm-tests/src/lib.rs
Labels: chore

#1461 linera-service uses fs_err for better errors
  Cargo.lock
  Cargo.toml
  linera-service/Cargo.toml
  linera-service/src/cli_wrappers/local_kubernetes_net.rs
  linera-service/src/cli_wrappers/local_net.rs
  linera-service/src/cli_wrappers/wallet.rs
  linera-service/src/config.rs
  linera-service/src/linera.rs
  linera-service/src/project.rs
  linera-service/src/server.rs
  linera-service/src/util.rs
Labels: enhancement

#1482 Create a `MockApplication` test helper type
  linera-execution/tests/test_execution.rs
  linera-execution/tests/utils/mock_application.rs
  linera-execution/tests/utils/mod.rs
Labels: refactor

#1412 Move to Helmfile
  .github/workflows/kubernetes.yml
  Cargo.lock
  Cargo.toml
  docker/server-entrypoint.sh
  docker/server-init.sh
  kubernetes/linera-validator/Chart.lock
  kubernetes/linera-validator/helmfile.yaml
  kubernetes/linera-validator/scylla-operator.values.yaml
  kubernetes/linera-validator/scylla.values.yaml
  kubernetes/linera-validator/templates/scylladb.yaml
  kubernetes/linera-validator/values-local.yaml
  linera-service/Cargo.toml
  linera-service/src/cli_wrappers/helm.rs
  linera-service/src/cli_wrappers/helmfile.rs
  linera-service/src/cli_wrappers/local_kubernetes_net.rs
  linera-service/src/cli_wrappers/mod.rs
Labels: enhancement

#1486 Fix missing application registration messages
  linera-execution/src/execution.rs
  linera-execution/src/lib.rs
  linera-execution/tests/test_execution.rs
Labels: bug

#1506 Reuse contract and service instances inside transaction
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/wasm/mod.rs
  linera-execution/tests/test_execution.rs
  linera-execution/tests/utils/mock_application.rs
  linera-sdk/src/log.rs
Labels: enhancement

#1519 Tweak default histogram buckets
  linera-chain/src/chain.rs
  linera-core/src/worker.rs
Labels: enhancement, low priority

#1527 Add `Resources` type for messages scheduled with Wasm
  examples/amm/src/contract.rs
  examples/crowd-funding/src/contract.rs
  examples/matching-engine/src/contract.rs
  linera-base/src/data_types.rs
  linera-execution/tests/fixtures/counter_contract.wasm
  linera-execution/tests/fixtures/counter_service.wasm
  linera-execution/tests/wasm.rs
  linera-sdk/contract.wit
  linera-sdk/src/contract/conversions_to_wit.rs
  linera-sdk/src/lib.rs
Labels: enhancement

#1541 Update resource counters with write operations
  linera-execution/src/execution_state_actor.rs
  linera-execution/src/resources.rs
  linera-execution/src/runtime.rs
  linera-execution/src/unit_tests/runtime_tests.rs
  linera-views/src/batch.rs
Labels: enhancement

#1545 Add some metrics related to execution
  Cargo.lock
  examples/Cargo.lock
  linera-base/src/prometheus_util.rs
  linera-chain/src/chain.rs
  linera-execution/Cargo.toml
  linera-execution/src/execution_state_actor.rs
  linera-execution/src/wasm/mod.rs
Labels: performance, chore

#1552 Update metrics in `linera-views` to use Prometheus helpers
  linera-views/src/metering.rs
Labels: refactor

#1563 Measure lock contention in `ChainGuards`
  linera-storage/src/chain_guards.rs
Labels: performance

#1564 Added command to subscribe and unsubscribe to other chains
  CLI.md
  Cargo.lock
  examples/Cargo.lock
  linera-execution/Cargo.toml
  linera-execution/src/system.rs
  linera-service/src/linera/client_options.rs
  linera-service/src/linera/main.rs
Labels: enhancement

#1592 Measure the latency to load a chain
  linera-storage/src/db_storage.rs
Labels: performance, chore
