Repository linera-io/linera-protocol, pull requests merged in 2024-07, with the labels that each got.

#2205 Revert "Make `SyncRuntime` represent the execution lifetime (#2192)"
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/test_utils/mock_application.rs
  linera-execution/src/unit_tests/runtime_tests.rs
  linera-execution/src/wasm/mod.rs
  linera-execution/src/wasm/system_api.rs
  linera-sdk/src/bin/wit_generator.rs
Labels: bug

#2203 Rename instances of linera-test to linera
  .github/workflows/docker.yml
  docker/compose.sh
  docker/docker-compose.yml
  kubernetes/linera-validator/helmfile.yaml
  linera-service/src/cli_wrappers/local_kubernetes_net.rs
  linera-service/src/linera/main.rs
Labels: chore

#2207 Make `SyncRuntime` represent the execution lifetime (second attempt)
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/test_utils/mock_application.rs
  linera-execution/src/unit_tests/runtime_tests.rs
  linera-execution/src/wasm/mod.rs
  linera-execution/src/wasm/system_api.rs
  linera-sdk/src/bin/wit_generator.rs
Labels: enhancement

#2209 Run service runtime as an actor spawned by the chain worker
  linera-chain/src/chain.rs
  linera-core/src/chain_worker/actor.rs
  linera-core/src/chain_worker/state.rs
  linera-execution/src/execution.rs
  linera-execution/src/execution_state_actor.rs
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/test_utils/mod.rs
  linera-execution/src/unit_tests/runtime_tests.rs
  linera-execution/tests/test_execution.rs
  linera-execution/tests/test_system_execution.rs
  linera-execution/tests/wasm.rs
Labels: refactor

#2210 Fix conflicting `ChainWorkerActor`s when running benchmarks
  linera-core/src/client.rs
  linera-core/src/local_node.rs
  linera-service/src/linera/client_context.rs
  linera-service/src/linera/main.rs
Labels: bug

#2221 `linera-client`: fix block height race
  linera-chain/src/manager.rs
  linera-core/src/client.rs
Labels: bug

#2222 Improve logging in README tests
  linera-service/tests/readme_test.rs
Labels: testing

#2226 Improve `ChainWorkerActor` logging
  linera-core/src/chain_worker/actor.rs
Labels: chore

#2216 Make application services keep running across queries
  linera-chain/src/chain.rs
  linera-core/src/chain_worker/actor.rs
  linera-core/src/chain_worker/state.rs
  linera-core/src/unit_tests/worker_tests.rs
  linera-execution/src/execution.rs
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/test_utils/mock_application.rs
  linera-execution/src/test_utils/mod.rs
  linera-execution/tests/test_execution.rs
  linera-execution/tests/test_system_execution.rs
  linera-execution/tests/wasm.rs
  linera-sdk/src/service/mod.rs
Labels: enhancement

#2246 Unfreeze time in long-lived service tests
  linera-core/src/unit_tests/worker_tests.rs
Labels: testing

#2258 Cache the LLM model inside the service
  examples/llm/README.md
  examples/llm/src/lib.rs
  examples/llm/src/service.rs
Labels: performance

#2263 Check the hash of the model and tokenizer bytes
  examples/Cargo.lock
  examples/llm/Cargo.toml
  examples/llm/src/service.rs
Labels: enhancement

#2269 Improve logs in LLM example
  examples/llm/src/service.rs
Labels: chore

#2277 Fix contention for `WorkerState` in SDK integration test framework
  linera-sdk/src/test/block.rs
  linera-sdk/src/test/chain.rs
  linera-sdk/src/test/validator.rs
Labels: performance

#2278 Add test helpers for native token transfers
  linera-sdk/src/test/block.rs
  linera-sdk/src/test/validator.rs
Labels: enhancement

#2280 Mint all native tokens when creating admin chain
  linera-sdk/src/test/validator.rs
Labels: bug

#2287 Benchmark cross-chain transfers without IO in CI
  .github/workflows/benchmarks.yml
  Cargo.lock
  linera-sdk/src/test/validator.rs
  linera-service/Cargo.toml
  linera-service/benches/transfers.rs
Labels: performance

#2290 `linera-core`: remove double-locking behaviour
  linera-base/src/crypto.rs
  linera-client/src/client_context.rs
  linera-core/src/client.rs
  linera-core/src/data_types.rs
  linera-core/src/local_node.rs
  linera-core/src/node.rs
  linera-core/src/unit_tests/test_utils.rs
  linera-core/src/unit_tests/wasm_worker_tests.rs
  linera-core/src/unit_tests/worker_tests.rs
  linera-core/src/updater.rs
  linera-core/src/worker.rs
  linera-rpc/src/client.rs
  linera-rpc/src/grpc/client.rs
  linera-rpc/src/grpc/server.rs
  linera-rpc/src/mass_client.rs
  linera-rpc/src/simple/client.rs
  linera-rpc/src/simple/server.rs
  linera-sdk/src/test/chain.rs
  linera-service/src/linera/main.rs
  linera-service/src/schema_export.rs
Labels: refactor

#2297 Benchmark `ReentrantCollectionView::try_load_all_entries`
  Cargo.lock
  linera-views/Cargo.toml
  linera-views/benches/reentrant_collection_view.rs
Labels: refactor

#2274 Fix `ReentrantCollectionView::has_pending` returning `true` if it has cached but unchanged entries
  linera-views/src/reentrant_collection_view.rs
  linera-views/src/unit_tests/views.rs
Labels: bug

#2273 Assert that there are no pending changes before chain worker operations
  linera-core/src/chain_worker/state.rs
  linera-core/src/chain_worker/state/attempted_changes.rs
  linera-core/src/chain_worker/state/mod.rs
  linera-core/src/chain_worker/state/temporary_changes.rs
Labels: enhancement

#2324 Fix subscription race condition in social pub-sub test
  linera-service/tests/end_to_end_tests.rs
Labels: testing

#2325 Use `chunks_exact` when post-loading multiple entries
  linera-views/src/reentrant_collection_view.rs
Labels: refactor

#2330 Remove chain guards
  .github/workflows/rust.yml
  Cargo.lock
  examples/Cargo.lock
  linera-client/src/client_context.rs
  linera-client/src/unit_tests/chain_listener.rs
  linera-core/src/client.rs
  linera-core/src/unit_tests/test_utils.rs
  linera-storage/Cargo.toml
  linera-storage/src/chain_guards.rs
  linera-storage/src/db_storage.rs
  linera-storage/src/dynamo_db.rs
  linera-storage/src/lib.rs
  linera-storage/src/rocks_db.rs
  linera-storage/src/scylla_db.rs
  linera-storage/src/unit_tests/chain_guards.rs
  linera-storage/src/unit_tests/dynamo_db.rs
  linera-storage/src/unit_tests/rocks_db.rs
  linera-storage/src/unit_tests/scylla_db.rs
  scripts/check_chain_loads.sh
Labels: refactor

#2332 Tweak the README of the Gen-NFT example
  examples/gen-nft/README.md
  examples/gen-nft/src/lib.rs
Labels: documentation

#2333 Tweak chain race warning
  linera-storage/src/lib.rs
Labels: documentation
