Repository linera-io/linera-protocol, pull requests merged in 2024-05, with the labels that each got.

#1985 Separate storage interface for contracts and services
  Cargo.lock
  examples/Cargo.lock
  examples/counter/src/contract.rs
  examples/counter/src/service.rs
  linera-sdk/Cargo.toml
  linera-sdk/src/contract/mod.rs
  linera-sdk/src/contract/runtime.rs
  linera-sdk/src/contract/test_runtime.rs
  linera-sdk/src/contract/wit.rs
  linera-sdk/src/lib.rs
  linera-sdk/src/service/mod.rs
  linera-sdk/src/service/runtime.rs
  linera-sdk/src/service/test_runtime.rs
  linera-sdk/src/views/conversions_to_wit.rs
  linera-sdk/src/views/mock_key_value_store.rs
  linera-sdk/src/views/mod.rs
  linera-sdk/src/views/system_api.rs
  linera-sdk/src/views/test_context.rs
Labels: refactor

#1963 Oracle support in the core protocol
  Cargo.lock
  examples/Cargo.lock
  examples/counter/README.md
  examples/counter/src/lib.rs
  examples/meta-counter/README.md
  examples/meta-counter/src/contract.rs
  examples/meta-counter/src/lib.rs
  linera-base/Cargo.toml
  linera-base/src/data_types.rs
  linera-chain/src/chain.rs
  linera-chain/src/data_types.rs
  linera-chain/src/lib.rs
  linera-chain/src/manager.rs
  linera-chain/src/test.rs
  linera-chain/src/unit_tests/chain_tests.rs
  linera-chain/src/unit_tests/data_types_tests.rs
  linera-core/src/unit_tests/wasm_client_tests.rs
  linera-core/src/unit_tests/wasm_worker_tests.rs
  linera-core/src/unit_tests/worker_tests.rs
  linera-core/src/worker.rs
  linera-execution/Cargo.toml
  linera-execution/src/execution.rs
  linera-execution/src/execution_state_actor.rs
  linera-execution/src/lib.rs
  linera-execution/src/runtime.rs
  linera-execution/src/unit_tests/runtime_tests.rs
  linera-execution/src/wasm/system_api.rs
  linera-execution/tests/fee_consumption.rs
  linera-execution/tests/fixtures/counter_contract.wasm
  linera-execution/tests/fixtures/counter_service.wasm
  linera-execution/tests/test_execution.rs
  linera-execution/tests/test_system_execution.rs
  linera-execution/tests/wasm.rs
  linera-explorer/src/components/Block.test.ts
  linera-explorer/src/components/Blocks.test.ts
  linera-explorer/src/entrypoint.rs
  linera-rpc/src/grpc/conversions.rs
  linera-rpc/tests/format.rs
  linera-rpc/tests/snapshots/format__format.yaml.snap
  linera-sdk/Cargo.toml
  linera-sdk/src/contract/runtime.rs
  linera-sdk/src/contract/test_runtime.rs
  linera-sdk/src/ethereum.rs
  linera-sdk/src/lib.rs
  linera-sdk/wit/contract-system-api.wit
  linera-sdk/wit/service-system-api.wit
  linera-service-graphql-client/gql/service_requests.graphql
  linera-service-graphql-client/gql/service_schema.graphql
  linera-service-graphql-client/src/service.rs
Labels: enhancement

#1993 Make applications handle their own state
  examples/amm/src/contract.rs
  examples/amm/src/service.rs
  examples/counter/src/contract.rs
  examples/counter/src/service.rs
  examples/crowd-funding/src/contract.rs
  examples/crowd-funding/src/service.rs
  examples/fungible/src/contract.rs
  examples/fungible/src/service.rs
  examples/llm/src/contract.rs
  examples/llm/src/service.rs
  examples/matching-engine/src/contract.rs
  examples/matching-engine/src/service.rs
  examples/matching-engine/src/state.rs
  examples/meta-counter/src/contract.rs
  examples/meta-counter/src/service.rs
  examples/native-fungible/src/contract.rs
  examples/native-fungible/src/service.rs
  examples/non-fungible/src/contract.rs
  examples/non-fungible/src/service.rs
  examples/social/src/contract.rs
  examples/social/src/service.rs
  linera-execution/tests/fixtures/counter_contract.wasm
  linera-execution/tests/fixtures/counter_service.wasm
  linera-execution/tests/wasm.rs
  linera-sdk/README.md
  linera-sdk/src/contract/mod.rs
  linera-sdk/src/lib.rs
  linera-sdk/src/service/mod.rs
  linera-service/template/contract.rs.template
  linera-service/template/service.rs.template
Labels: refactor

#1994 Rename `new` and `finalize` to `load` and `store`
  examples/amm/src/contract.rs
  examples/counter/src/contract.rs
  examples/crowd-funding/src/contract.rs
  examples/fungible/src/contract.rs
  examples/llm/src/contract.rs
  examples/matching-engine/src/contract.rs
  examples/meta-counter/src/contract.rs
  examples/native-fungible/src/contract.rs
  examples/non-fungible/src/contract.rs
  examples/social/src/contract.rs
  linera-sdk/src/contract/mod.rs
  linera-sdk/src/lib.rs
  linera-service/template/contract.rs.template
Labels: refactor

#1995 Don't create `.cargo/config.toml` in new projects
  linera-service/src/project.rs
  linera-service/template/config.toml.template
Labels: chore

#1996 Clean-up example application READMEs and Cargo config
  .cargo/config.toml
  examples/amm/README.md
  examples/amm/src/lib.rs
  examples/counter/README.md
  examples/counter/src/lib.rs
  examples/fungible/README.md
  examples/fungible/src/lib.rs
  examples/native-fungible/README.md
  examples/native-fungible/src/lib.rs
  examples/non-fungible/README.md
  examples/non-fungible/src/lib.rs
Labels: chore

#2012 Pin `async-graphql` version
  Cargo.lock
  Cargo.toml
  examples/Cargo.lock
  examples/Cargo.toml
  linera-base/Cargo.toml
  linera-service/template/Cargo.toml.template
Labels: bug, chore

#2035 Limit network actions to tracked chains
  linera-core/src/client.rs
  linera-core/src/local_node.rs
  linera-core/src/unit_tests/client_test_utils.rs
  linera-core/src/worker.rs
  linera-service/src/linera/client_context.rs
  linera-service/src/linera/main.rs
Labels: bug

#2042 Limit network actions to tracked chains (in `devnet_2024_05_07`)
  linera-core/src/client.rs
  linera-core/src/local_node.rs
  linera-core/src/unit_tests/test_utils.rs
  linera-core/src/worker.rs
  linera-service/src/linera/client_context.rs
  linera-service/src/linera/main.rs
  linera-service/src/unit_tests/chain_listener.rs
Labels: performance

#2010 Create a `CertificateValueCache`
  linera-core/src/client.rs
  linera-core/src/lib.rs
  linera-core/src/unit_tests/value_cache_tests.rs
  linera-core/src/value_cache.rs
  linera-core/src/worker.rs
Labels: refactor

#2049 Promote reinserted values in cache
  linera-core/src/unit_tests/value_cache_tests.rs
  linera-core/src/value_cache.rs
Labels: enhancement

#2064 Fix `linera-sdk` docs.rs build
  linera-sdk/build.rs
  linera-sdk/src/bin/wit_generator.rs
  linera-sdk/src/test/mod.rs
Labels: bug, documentation

#2055 Split off `ChainWorkerState` from `WorkerState`
  linera-chain/src/chain.rs
  linera-chain/src/lib.rs
  linera-core/src/chain_worker/config.rs
  linera-core/src/chain_worker/mod.rs
  linera-core/src/chain_worker/state.rs
  linera-core/src/client.rs
  linera-core/src/data_types.rs
  linera-core/src/lib.rs
  linera-core/src/unit_tests/worker_tests.rs
  linera-core/src/worker.rs
  linera-sdk/src/test/chain.rs
Labels: refactor, performance

#2088 Refactor usage of `SocketAddr`
  linera-rpc/src/simple/server.rs
  linera-rpc/src/simple/transport.rs
  linera-service/src/prometheus_server.rs
  linera-service/src/proxy.rs
  linera-service/src/server.rs
Labels: refactor, performance

#2086 Listen for signals in the main task
  linera-service/src/linera/net_up_utils.rs
Labels: enhancement, performance
