Repository linera-io/linera-protocol, pull requests merged in 2025-04, with the labels that each got.

#3705 Replace `#[should_panic]` with assertions in HTTP example tests
  examples/how-to/perform-http-requests/tests/http_requests.rs
  linera-chain/src/lib.rs
  linera-core/src/worker.rs
  linera-sdk/src/test/block.rs
  linera-sdk/src/test/chain.rs
  linera-sdk/src/test/mod.rs
Labels: refactor

#3718 Allow the node service to select arbitrary ports
  CLI.md
  linera-client/src/client_options.rs
  linera-indexer/example/tests/test.rs
  linera-service/src/cli_wrappers/wallet.rs
  linera-service/src/linera/main.rs
  linera-service/src/node_service.rs
  linera-service/src/schema_export.rs
Labels: enhancement

#3783 Fix How To Perform HTTP Requests readme test in CI
  examples/how-to/perform-http-requests/README.md
  linera-service/tests/readme_test.rs
Labels: testing

#3830 `linera-service-graphql-client`: use `similar-asserts` for schema snapshot
  Cargo.lock
  linera-service-graphql-client/Cargo.toml
  linera-service-graphql-client/tests/test_check_service_schema.rs
Labels: chore
