Repository linera-io/linera-protocol, pull requests merged in 2025-09, with the labels that each got.

#4564 `linera-base`: expunge `wasmtimer` in favour of `kywasmtime`
  Cargo.lock
  Cargo.toml
  linera-base/Cargo.toml
  linera-base/src/time.rs
Labels: backport

#4577 Restructure `linera-web` directory
  .github/workflows/rust.yml
  .github/workflows/web.yml
  Cargo.toml
  docker/Dockerfile
  examples/pnpm-lock.yaml
  examples/pnpm-workspace.yaml
  examples/vite.config.ts
  web/.cargo/config.toml
  web/.gitignore
  web/@linera/client/Cargo.toml
  web/@linera/client/README.md
  web/@linera/client/build.bash
  web/@linera/client/clippy.toml
  web/@linera/client/docs/README.md
  web/@linera/client/docs/classes/Client.md
  web/@linera/client/docs/classes/Frontend.md
  web/@linera/client/docs/classes/Wallet.md
  web/@linera/client/docs/functions/default.md
  web/@linera/client/docs/functions/initSync.md
  web/@linera/client/docs/functions/wasm_thread_entry_point.md
  web/@linera/client/docs/interfaces/Signer.md
  web/@linera/client/docs/type-aliases/ReadableStreamType.md
  web/@linera/client/package.json
  web/@linera/client/src/lib.rs
  web/@linera/client/src/signer.d.ts
  web/@linera/client/src/signer.rs
  web/@linera/client/tsconfig.json
  web/@linera/client/typedoc.json
  web/@linera/signer/jest.config.ts
  web/@linera/signer/package.json
  web/@linera/signer/src/index.ts
  web/@linera/signer/src/metamask.ts
  web/@linera/signer/src/private-key.ts
  web/@linera/signer/tests/index.test.ts
  web/@linera/signer/tsconfig.build.json
  web/@linera/signer/tsconfig.json
  web/@linera/signer/typedoc.json
  web/README.md
  web/pnpm-workspace.yaml
  web/rust-toolchain.toml
Labels: refactor

#4578 `examples/vite.config.ts`: check for required environment variables
  examples/vite.config.ts
Labels: testing

#4583 Fix deploy-validator script to use remote Docker images by default
  docker/docker-compose.yml
  scripts/deploy-validator.sh
Labels: bug

#4584 Fix Docker Compose image tags for testnet_conway
  docker/docker-compose.yml
Labels: bug, backport

#4586 Fix Docker Compose validator deployment environment persistence
  docker/.env.production.template
  scripts/backup-validator-keys.sh
  scripts/deploy-validator.sh
  scripts/extract-wallet-from-volume.sh
  scripts/fix-validator-env.sh
Labels: bug

#4601 `linera-web`: bump to 0.15.4
  linera-web/package.json
  linera-web/signer/package.json
Labels: release

#4599 Native fungible demo accepts 32-byte long address
  examples/native-fungible/index.html
Labels: backport
