Repository linera-io/linera-protocol, pull requests merged in 2025-02, with the labels that each got.

#3273 Export `unstable-oracles` feature from `linera-service`
  linera-core/Cargo.toml
  linera-service/Cargo.toml
Labels: chore

#3298 Fix dangling endpoint to chain worker actor that failed to start
  linera-core/src/chain_worker/actor.rs
  linera-core/src/worker.rs
  linera-service/src/linera/main.rs
Labels: bug

#3144 Use service to query ethereum node in Ethereum Tracker example
  examples/ethereum-tracker/src/contract.rs
  examples/ethereum-tracker/src/lib.rs
  examples/ethereum-tracker/src/service.rs
  linera-sdk/src/ethereum.rs
Labels: enhancement

#3420 Pin the version of the `base64ct` indirect dependency
  Cargo.lock
  examples/Cargo.lock
  linera-sdk/Cargo.toml
Labels: chore

#3435 Remove `mut` from `ServiceRuntime::http_request`
  linera-sdk/src/service/runtime.rs
  linera-sdk/src/service/test_runtime.rs
Labels: refactor

#3422 `linera-service`: move `assign_new_chain_to_key` to `linera-client`
  linera-client/src/client_context.rs
  linera-client/src/error.rs
  linera-service/src/linera/main.rs
Labels: refactor
